Setup dinamicaly insert html and popup windows
Fernando426/Portfolio-mobile-website2 pull request #6
Opened 2023-07-26 15:23 UTC by Fernando426

- Added javascript code for the popup mobile menu
- Added CSS code for styles of popup mobile menu
- Added the information of the two collaborators to the Readme file
- The correct functioning of the linters and the absence of errors were verified

2023-07-26 16:05 UTC, AbelG101 requested changes
![](https://media.giphy.com/media/ReyD4OdRiHeLDCRaEP/giphy.gif)


# Hi @Fernando426 👋, 

You're doing a good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- Correct use of GitHub Flow ✔
- Well-structured files ✔
- All linter checks are passing ✔
- Descriptive PR title with a great summary ✔

## Required Changes ♻️
- _Check the comments under the review._
- you just have to make a few changes and you're on your way 🚀.


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-26 16:05 UTC, AbelG101 commented on style.css
- [ ] Please ensure that you closely follow the Figma design when implementing it, as I have noticed some discrepancies in your current design. Here are the specific areas that need attention:
    - The project image in the Figma design takes up almost 60% of the modal's width, and its height matches that of the description. Please adjust your design to match this.
    - Kindly make sure to use the proper font and text color specified in the original design.
    - The buttons in your design currently use the default border style of the browser. Please fix this and implement the different interactions, such as hover and active (pressed), as specified in the Figma design.
    - The modal card in the Figma design is centered both vertically and horizontally. However, your design seems to be misaligned. Additionally, there is a blur effect in the background of the popup in the original design. Please make sure to implement these correctly.
- Figma design:
  ![image](https://github.com/Fernando426/Portfolio-mobile-website2/assets/104968236/edea42c5-5fa6-4519-8487-6649e9d4d2ec)
- Your design:
  ![image](https://github.com/Fernando426/Portfolio-mobile-website2/assets/104968236/7da12cf5-4ec4-4d2c-aa46-aac4c74bb39c)
- [ ] This also applies to the mobile version so make sure it looks good on mobile as well.

2023-07-26 16:05 UTC, AbelG101 commented on style.css
- [ ] I noticed that the popup on the mobile version overflows when there is not enough vertical space. This could lead to a poor user experience. To address this, I would suggest adding a scroll feature using CSS so that the text does not overflow.
- Here's how it looks:
  ![image](https://github.com/Fernando426/Portfolio-mobile-website2/assets/104968236/c1f03693-06f4-48ad-8547-a9aa510d8c21)

2023-07-26 16:05 UTC, AbelG101 commented on assets/script.js
>            </div>
- [ ] I noticed that the popup modal is currently using static data that has been hard-coded. However, since each project's information is unique, it would be better to use the projects array that you have created to dynamically load the popup. This would make the code more flexible and scalable.

2023-07-26 16:05 UTC, AbelG101 commented on style.css
- [ ] As part of the project requirements, the project section should be created dynamically. However, I noticed that you forgot to remove the first project card from that section, and it still exists in the HTML. Please ensure that you remove this card and load it dynamically, just like you did for the rest of the project cards. This will ensure consistency in your code and the proper functioning of the project section.
  ![image](https://github.com/Fernando426/Portfolio-mobile-website2/assets/104968236/ea70370f-1566-450c-a25f-ef527ee3da14)

2023-07-26 16:05 UTC, AbelG101 commented on assets/script.js
- [ ] I noticed that there is some commented code in your script. Please remove it, as it is unnecessary and can make the code harder to read and understand. Keeping commented code can also lead to confusion and errors in the future.
  ![image](https://github.com/Fernando426/Portfolio-mobile-website2/assets/104968236/b4d825c2-f9b1-4070-9d32-7115589ca874)

2023-07-26 21:32 UTC, shahadat3669 requested changes
Hi @Fernando426 @JhonatanErosa , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


<img src="https://media2.giphy.com/media/m3864rBwwBTKMAbpn3/giphy.gif"/>

## Don't Worry 🙏

It's okay to have bugs in your code. 🆗 Please see this code review as an opportunity to learn practical coding skills and discover new tips that can improve your code quality 💯 and help you **get even better** 💼.

**I will guide you on how to address these areas down below 👇.**

## Highlights
✅ No linter Errors
✅ Descriptive PR Title
✅ Descriptive PR Description



 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

## Have any doubt ❓

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

<table  width="100%" align="center">
  <tr>
    <td colspan="4" align="center">
      <strong>Contact me: Shahadat Hossain</strong>
    </td>
  </tr>
  <tr>
    <td align="center">
      <a href="https://github.com/shahadata3669">
        <img src="https://img.shields.io/badge/github-%23121011.svg?style=for-the-badge&logo=github&logoColor=white" alt="GitHub">
      </a>
    </td>
    <td align="center">
      <a href="https://www.linkedin.com/in/shahadat-cseng/">
        <img src="https://img.shields.io/badge/linkedin-%230077B5.svg?style=for-the-badge&logo=linkedin&logoColor=white" alt="LinkedIn">
      </a>
    </td>
    <td align="center">
      <a href="https://app.slack.com/client/T47CT8XPG/D05GT4E4WAY/rimeto_profile/U04426SD71V">
        <img src="https://img.shields.io/badge/Slack-4A154B?style=for-the-badge&logo=slack&logoColor=white" alt="Slack">
      </a>
    </td>
    <td align="center">
      <a href="mailto:shahadat3669@gmail.com?subject=Microverse%20Code%20Review">
        <img src="https://img.shields.io/badge/Gmail-D14836?style=for-the-badge&logo=gmail&logoColor=white" alt="Email">
      </a>
    </td>
  </tr>
</table>

## ⚠️ WARNING ⚠️

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-26 21:32 UTC, shahadat3669 commented on style.css
👋 Thank you for your hard work on the project! I see that you have made some updates, but there are still some areas that need attention to closely match the Figma design. Here are the specific areas that require further adjustments:
- The image of the project in the Figma design should take up almost 60% of the modal's width, and its height should match that of the description. Please adjust your design to match this proportion for a better visual representation.
- You've updated the font styles for the title, but you forgot to update the color as specified in the design. Make sure to follow the design and update the font color accordingly.
- Your font size and font weight match the design for the description, but you forgot to update the color and line height for the mobile version. Make sure to follow the design and update the font color accordingly.
- Similarly, for the technologies section, you've updated the font styles, but you also need to update the color and font styles for the desktop version. Please make sure to apply the correct styles for both mobile and desktop versions to ensure consistency and better accessibility.
- As mentioned in the previous review, there is an issue with the default border style of the button. It's essential to fix this and implement different interactions, such as hover and active (pressed), as specified in the Figma design.
![image](https://github.com/Fernando426/Portfolio-mobile-website2/assets/55840999/4342a4c2-618e-4114-9cd2-3599037a0a1a)
- The modal card in the Figma design should be centered both vertically and horizontally. However, in your current design, it seems to be misaligned. Additionally, there is a blur effect in the background of the popup in the original design. Please make sure to implement these correctly to achieve the desired appearance.
![image](https://github.com/Fernando426/Portfolio-mobile-website2/assets/55840999/ec2bcb84-9e93-43dc-86e9-0d6858e4d3d3)

By paying attention to these details and following the Figma design closely, you can create a more polished and visually appealing project. Keep up the good work, and don't hesitate to reach out if you have any questions or need further assistance. Happy coding! 🚀💻🎨

2023-07-26 21:32 UTC, shahadat3669 commented on style.css
- [ ] Thank you for addressing the previous request to remove the overflow. However, it seems that a new issue has arisen with the modal. Now, there's a problem with scrolling down to view the entire modal content on the mobile version, as shown in the video below: 

[Document3.webm](https://github.com/Fernando426/Portfolio-mobile-website2/assets/55840999/403c311f-d699-4458-b326-08f28d704b97)

By setting a maximum height for the modal container and enabling vertical scrolling when the content exceeds the available height, the modal should become scrollable on mobile devices. Keep up the good work and stay persistent in your learning journey! 🌟🚀💻

2023-07-26 21:32 UTC, shahadat3669 commented on assets/script.js
🎉👍 Thank you for your effort in adding the popup functionality to your project! 🌟 This is a significant step forward in making your project more interactive and user-friendly. However, as mentioned by the previous reviewer, there's a crucial aspect that needs attention.

- [ ] 📝💡 The popups should be populated dynamically based on the project details. Currently, the popup content remains the same for all projects, which is not aligned with the project requirements. 💻🔧 To resolve this, you'll need to dynamically generate the content for each project's popup. When a user clicks on the "Show Project" button, the popup should display the relevant information for that specific project, such as title, description, technologies used, live demo link, and project source code link. 

🚀📝 By making these adjustments, your project will be more in line with the design requirements and provide a better user experience by displaying accurate and relevant information for each project. 👏🌈 Keep up the good work and happy coding! You're doing great! 💪🎉🚀

2023-07-27 07:23 UTC, Fernando426 commented
With all due respect I would like to mention that Knowledge should be used to help as many as possible! never to make anyone stumble. They have been asking me for unnecessary changes for the current level of my project and the program, I know several portfolios of colleagues who are already in advanced modules that do not comply with what they ask of me here! that is
because most reviewers have completely different criteria when reviewing someone else's code. In the same way I have made an effort making the requested changes, Thank you for your review in any case!

2023-07-27 08:37 UTC, zainsadaqat approved these changes
# Pull Request Approved ✅ 🎊 🎉 
## Hello @Fernando426  👋 

### Things to appreciate
- [ ] Good job for implementing the things requested by the previous code reviewers. 👍 

### Your project is complete!  There is nothing else to say other than it's time to merge it.

# Congratulations!!! 🎉 🥳 👏 🙌 🎊 ☑️ 

<img src="https://media1.giphy.com/media/3KC2jD2QcBOSc/giphy.gif"/>

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-27 21:21 UTC, merged